<?php
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/../includes/delegates.php';
ensureDelegateClaimsSchema($pdo);
if(empty($_SESSION['claims_csrf'])) $_SESSION['claims_csrf']=bin2hex(random_bytes(32));
$msg='';$statuses=['Pending','Approved','Rejected','Paid'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!hash_equals($_SESSION['claims_csrf'],(string)($_POST['csrf_token']??''))) $msg='<div class="alert alert-danger">The request expired. Please try again.</div>';
    else {
        $id=(int)($_POST['claim_id']??0);$status=(string)($_POST['status']??'');$note=trim((string)($_POST['admin_note']??''));
        if($id<1||!in_array($status,$statuses,true)||mb_strlen($note)>500) $msg='<div class="alert alert-warning">Invalid claim update.</div>';
        else {$stmt=$pdo->prepare('UPDATE delegate_expense_claims SET status=?,admin_note=? WHERE id=?');$stmt->execute([$status,$note?:null,$id]);recordActivity($pdo,'delegate_expense_claim_reviewed','delegate_expense_claim',$id,'Administrator updated an expense claim.',['status'=>$status],(int)$_SESSION['id'],'admin',$_SESSION['username']);$msg='<div class="alert alert-success">Claim updated.</div>';}
    }
}
$claims=$pdo->query("SELECT c.*,a.first_name,a.last_name,u.country_name,u.username AS delegation_username FROM delegate_expense_claims c JOIN athletes a ON a.id=c.athlete_id JOIN users u ON u.id=a.country_id ORDER BY FIELD(c.status,'Pending','Approved','Rejected','Paid'),c.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);
$pendingCount=count(array_filter($claims,fn($c)=>$c['status']==='Pending'));
$claimTotals=[];foreach($claims as $claim){$claimTotals[$claim['currency']]=($claimTotals[$claim['currency']]??0)+(float)$claim['amount'];}
$adminTotalData=['count'=>count($claims),'pending'=>$pendingCount,'amounts'=>[]];foreach($claimTotals as $currency=>$amount)$adminTotalData['amounts'][]=$currency.' '.number_format($amount,2);if(!$adminTotalData['amounts'])$adminTotalData['amounts'][]='MYR 0.00';
register_shutdown_function(static function () use ($adminTotalData): void {$amountHtml='';foreach($adminTotalData['amounts'] as $total)$amountHtml.='<div>'.htmlspecialchars($total).'</div>';$html='<div class="col-md-4"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted small">Total Claims</div><div class="fs-3 fw-bold">'.$adminTotalData['count'].'</div></div></div></div><div class="col-md-4"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted small">Pending Claims</div><div class="fs-3 fw-bold text-warning">'.$adminTotalData['pending'].'</div></div></div></div><div class="col-md-4"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted small">Total Claimed</div><div class="fw-bold">'.$amountHtml.'</div></div></div></div>';echo '<script>(()=>{const card=document.querySelector("main>.card");if(!card)return;const box=document.createElement("div");box.className="row g-3 mb-4";box.innerHTML='.json_encode($html).';card.before(box);})();</script>';});
require_once __DIR__.'/includes/header.php';
?>
<div class="d-flex justify-content-between align-items-center border-bottom pb-2 mb-4"><div><h1 class="h2 mb-1">Expense Claims</h1><p class="text-muted mb-0">Review claims submitted by delegates.</p></div><span class="badge text-bg-warning fs-6"><?php echo $pendingCount;?> pending</span></div><?php echo $msg;?><div class="card shadow-sm"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead class="table-light"><tr><th>Delegate</th><th>Expense</th><th>Description</th><th class="text-end">Amount</th><th>Receipt</th><th style="min-width:260px">Review</th></tr></thead><tbody><?php foreach($claims as $claim):?><tr><td><div class="fw-semibold"><?php echo htmlspecialchars($claim['first_name'].' '.$claim['last_name']);?></div><div class="small text-muted"><?php echo htmlspecialchars($claim['country_name']?:$claim['delegation_username']);?><br>Submitted <?php echo htmlspecialchars(date('d M Y',strtotime($claim['created_at'])));?></div></td><td><div><?php echo htmlspecialchars(date('d M Y',strtotime($claim['expense_date'])));?></div><span class="badge text-bg-light border text-dark"><?php echo htmlspecialchars($claim['category']);?></span></td><td><?php echo htmlspecialchars($claim['description']);?></td><td class="text-end text-nowrap fw-semibold"><?php echo htmlspecialchars($claim['currency']);?> <?php echo number_format((float)$claim['amount'],2);?></td><td><?php if($claim['receipt_path']):?><a class="btn btn-sm btn-outline-secondary" href="claim_receipt.php?id=<?php echo (int)$claim['id'];?>"><i class="bi bi-paperclip"></i> View</a><?php else:?><span class="text-muted">None</span><?php endif;?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['claims_csrf']);?>"><input type="hidden" name="claim_id" value="<?php echo (int)$claim['id'];?>"><div class="input-group input-group-sm mb-2"><select class="form-select" name="status"><?php foreach($statuses as $status):?><option<?php echo $claim['status']===$status?' selected':'';?>><?php echo $status;?></option><?php endforeach;?></select><button class="btn btn-primary">Save</button></div><input class="form-control form-control-sm" name="admin_note" maxlength="500" value="<?php echo htmlspecialchars((string)$claim['admin_note']);?>" placeholder="Optional note for delegate"></form></td></tr><?php endforeach;?><?php if(!$claims):?><tr><td colspan="6" class="text-center text-muted py-4">No expense claims submitted.</td></tr><?php endif;?></tbody></table></div></div></div>
<?php require_once __DIR__.'/includes/footer.php';?>
