<?php
require_once 'includes/auth.php';
require_once '../includes/volunteers.php';
$stmt=$pdo->prepare('SELECT * FROM volunteer_applications WHERE user_id=? LIMIT 1'); $stmt->execute([$currentUser['id']]); $application=$stmt->fetch(PDO::FETCH_ASSOC);
if (!$application) { http_response_code(404); exit('Volunteer profile not found.'); }
$language=($_GET['lang'] ?? $_SESSION['volunteer_language'] ?? 'ms')==='en'?'en':'ms'; $t=static fn($ms,$en)=>$language==='en'?$en:$ms; $pageTitle=$t('Papan Pemuka Sukarelawan','Volunteer Dashboard');
require 'includes/header.php';
?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1"><?php echo $t('Selamat datang','Welcome'); ?>, <?php echo htmlspecialchars($application['full_name']); ?></h1><p class="text-muted mb-0"><?php echo $t('Profil sukarelawan MSDeaf anda','Your MSDeaf volunteer profile'); ?></p></div><span class="badge bg-success fs-6"><?php echo $t('Diluluskan','Approved'); ?></span></div>
<div class="row g-4"><div class="col-md-7"><div class="card"><div class="card-body p-4"><h2 class="h5 text-primary mb-3"><?php echo $t('Maklumat Permohonan','Application Details'); ?></h2><dl class="row mb-0"><dt class="col-sm-5"><?php echo $t('Bahagian','Department'); ?></dt><dd class="col-sm-7"><?php echo $application['department']==='technical'?$t('Teknikal','Technical'):$t('Sekretariat','Secretariat'); ?></dd><dt class="col-sm-5"><?php echo $t('Ketersediaan','Availability'); ?></dt><dd class="col-sm-7"><?php echo htmlspecialchars($application['available_from']); ?><?php echo $application['available_until']?' – '.htmlspecialchars($application['available_until']):''; ?></dd><dt class="col-sm-5"><?php echo $t('Saiz T-shirt','T-shirt size'); ?></dt><dd class="col-sm-7"><?php echo htmlspecialchars($application['tshirt_size']); ?></dd><dt class="col-sm-5"><?php echo $t('Penginapan','Accommodation'); ?></dt><dd class="col-sm-7"><?php echo $application['accommodation_required']?$t('Diperlukan','Required'):$t('Tidak diperlukan','Not required'); ?></dd></dl></div></div></div><div class="col-md-5"><div class="card"><div class="card-body p-4"><h2 class="h5 text-primary mb-3"><?php echo $t('Maklumat Hubungan','Contact Details'); ?></h2><p><i class="bi bi-envelope me-2"></i><?php echo htmlspecialchars($application['email']); ?></p><p class="mb-0"><i class="bi bi-whatsapp me-2"></i><?php echo htmlspecialchars($application['whatsapp']); ?></p></div></div></div></div>
<?php require 'includes/footer.php'; ?>
